### PR TITLE
XGtE Errata

### PR DESCRIPTION
**Pull request by BraabHimself**
https://media.wizards.com/2020/dnd/downloads/XGtE-Errata.pdf

### CODE REVIEW

**Comment by BraabHimself** [comment]
> Have you ensured that these changes don't cause the text to overflow?

The only change that would cause overflow is the changes to the Talking Doll. I removed the word "stuffed" from the description to ensure there's enough room.

**Comment by BraabHimself** [comment]
Ok. I took a stab at the description.

**Comment by Smashman** [comment]
I think add a semicolon after `5-ft cube`, otherwise it reads like only 5ft cube creatures can be healed!

- [ ] Semicolon after `5-ft cube`

**Comment by BraabHimself** [comment]
There you go. Was worried that semicolon would cause overflow, but it worked out.

**Comment by safety-orange** [comment]
I'm going to make everybody's live harder again, my apologies.

> Healing Spirit

The "any" is there, as explained in the glossary, to show that you **can** trigger this, but it isn't mandatory. For stuff that always hits everybody, the sheet uses "all". Thus, I'm going to change it to `"5-ft cube; any living crea I see start/enter heals 1d6+1d6/SL HP; 1+spell mod uses; bns a move it 30 ft"`.

> Life Transference

As there is still plenty space left for this spell, I think we can also add this change and make it `"I take 4d8+1d8/SL Necrotic dmg (in full), and 1 crea in range I can see heals twice that in HP"`.

Let me know if you don't agree with these changes!

**Comment by BraabHimself** [comment]
I'll defer to you on spell descriptions. I've heard whispers you're the best at them. :)

**Pull request merged**
