### PR TITLE
Use custom word boundary that considers + as part of the word

### PR DESCRIPTION
**Pull request by Smashman**

### CODE REVIEW

**Comment by safety-orange** [comment]
Thank you for the suggested edit, but unfortunately AcroJS doesn't support lookbehinds for regular expressions (`?<!` and `?<=`).

**Comment by safety-orange** [comment]
I have come up with another approach, by changing `\b(2|two)` to `((^|[^+-]\b)2|\btwo)`. Thus, it now only checks for the + and - signs, but that should be enough, because there should be little other reason why you use a "2" in the description or name of an attack.

I'm closing this commit now, but be free to open it if you think of a better way this can (should) be handled.

**Comment by Smashman** [comment]
I'm pretty sure I tested it and it worked. 🤔

**Comment by morepurplemorebetter** [comment]
All I get is the error "SyntaxError: invalid quantifier", using the latest version of Adobe Acrobat Pro DC:
image

**Comment by safety-orange** [comment]
All I get is the error "SyntaxError: invalid quantifier", using the latest version of Adobe Acrobat Pro DC:
image

**Pull request closed without merging**
