### PR TITLE
Add Port Nyanzaru equipment

### LINKED ISSUE #10: ToA equipment
In Tomb of Annihilation there are items that can be purchased, such as Insect Repellent and Raincatchers.

These would be very useful in the automation.

Thanks.

Item | Price | Amount | Weight
--- | --- | --- | ---
Block of Incense | 1 sp | 1 | -
Vial of Salve | 1 gp | 20 (applications) | -
Rain Catcher | 1 gp | 1 | 5lb

### PR DESCRIPTION
**Pull request by Smashman**
Fixes #10.

### CODE REVIEW

**Comment by Smashman** [comment]
Hm, this doesn't appear to do work as expected..!

**Comment by safety-orange** [comment]
They work, but only after saving the sheet and opening it again do they appear in the menu. I see that MPMB has fixed this for the next version of the sheet on his GitHub.

The gearlist entries do need a source, so that they only show up if that source is included. If no source is listed, they will always be included and I think that is not what we want for these kind of additions :)

**Comment by Smashman** [comment]
I noticed that there's no 'equipment' menu in the source selection dialog.

**Comment by safety-orange** [comment]
Great work, I merged it :)

I don't know why equipment isn't an option in the source selection dialog. Perhaps it was deemed not so necessary?

I also see that the syntax is missing this, I'll pass it along to MPMB!

**Pull request merged**
