### PR TITLE
Update wording on Divine Magic: Neutrality description

### LINKED ISSUE #12: Clumsily written sentence in Divine Sorcerer
https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/blob/cfe69a0b89b8dd656d9f88973321debcfd896edf/WotC%20material/pub_20171121_XGtE.js#L1927

I see why it's written differently to the others, but I am sure there's a grammatically better way of saying this?

Also, what is the recommended character limit per line?

### PR DESCRIPTION
**Pull request by Smashman**
Fixes #12

### CODE REVIEW

**Comment by safety-orange** [comment]
The 'i' of 'it' should be capitalized to adhere to how the rest of the descriptions are written. I'm also not really convinced we should start using an abbreviation for number, as it isn't used anywhere else.

**Comment by Smashman** [comment]
While I don't disagree with the 'num' shortening, it's better than the sentence that is currently in place, which is difficult to parse. "Num" is a fairly common shortening for number and should cause less confusion.
Regarding the capitalisation after the semicolon, I do disagree with that. Words should not be capitalised after a semicolon and if there are other places that have capitalisation after a semicolon, I believe this should be corrected.

Thanks.

**Comment by safety-orange** [comment]
I'm not going to correct the hundreds of places that the semicolon is used to indicate the end of a sentence, I'm sorry.

**Comment by Smashman** [comment]
I am not sure why this results in a closing of this PR.
The confusingly written sentence is still present.
I could replace each of the capitalised words after semicolons quite easily with a find and replace.
If that is not an acceptable resolution, I would be happier with capitalising the 'it' in order to fix the current sentence.

**Pull request closed without merging**
