### PR TITLE
Use gulp for platform agnostic minification and concatenation

### PR DESCRIPTION
**Pull request by Smashman**
This also removes superfluous `iFileName`s and `RequiredSheetVersion`s

### CODE REVIEW

**Comment by Smashman** [comment]
The changes to the minified files look significant, this is due to the line end changes which will now remain consistent no matter which platform is used.

**Comment by RobRoseKnows** [comment]
Does minification yield any performance improvements? Because currently I personally don't see a need for it since the imports aren't served via the web.

**Comment by Smashman** [comment]
While I don't disagree, I am simply reimplementing the existing functionality using gulp to remove the PowerShell requirement.

They are _sort of_ shared online via the reddit post, however.

**Comment by safety-orange** [comment]
> Does minification yield any performance improvements? Because currently I personally don't see a need for it since the imports aren't served via the web.

I did some tests with the PDF and although the performance improvements after loading the PDF are indeed very small, opening the PDF with the scripted saved in it did go significantly faster. All in all, the difference is probably negligible. Your average smarthphone is still going to crash Adobe Acrobat Reader when trying to open this sheet with the script loaded.

Also, this way the PDF uses less space with the script loaded. That doesn't make any difference to me (what is 500 KB nowadays anyway?), but I have had numerous people complain about the size of these PDFs and I figured I could do my part to reduce its size a bit.

**Comment by Smashman** [comment]
This PR is still open, any issues precluding merge?
Thanks

**Pull request merged**
