### PR TITLE
MBUG-30

### PR DESCRIPTION
**Pull request by BraabHimself**
Remove force damage from description

### CODE REVIEW

**Comment by Smashman** [comment]
Is this `weaponOptions` object even necessary if it's a regular staff?

**Comment by Smashman** [comment]
Ah it's +1. I'd remove `description` entirely and let `baseWeapon` handle that.

**Comment by BraabHimself** [comment]
Done

**Comment by Smashman** [comment]
(I am assuming that works as intended. You tested right?)

**Comment by BraabHimself** [comment]
Removing the description completely has the intended effect.

**Comment by Smashman** [comment]
Great :+1:

**Review by Smashman — APPROVED** [review]

**Pull request merged**
