### PR TITLE
Add Oversized Longbow to WDH

### PR DESCRIPTION
**Pull request by BraabHimself**
Add Oversized Longbow and Oversized Arrow to WDH

### CODE REVIEW

**Comment by Smashman** [comment]
As with #45, I would recommend removing all minified files and simply commit `WotC material/v13/pub_20180918_WDH.js`

**Comment by safety-orange** [comment]
The description is very long and uses an abbreviation that isn't used anywhere else in the sheet "w/". I think the description of the weapon is better done as "Ammunition, heavy, two-handed; Damage uses Str instead of Dex; Requires Medium size and Str 18".

Also, the ability is set to Str, but it should be Dex, because all ranged weapon use Dex for the attack roll. Then there needs to be a `modifiers` to remove the Dex bonus and add the Str bonus to the damage.

```JavaScript
WeaponsList["oversized longbow"] = {
	regExpSearch : /^(?=.*oversized?)(?=.*longbow).*$/i,
	name : "Oversized Longbow",
	source : ["WDH", 201],
	list : "ranged",
	ability : 2,
	type : "Martial",
	damage : [2, 6, "piercing"],
	range : "150/600 ft",
	weight : 2,
	description : "Ammunition, heavy, two-handed; Damage uses Str instead of Dex; Requires Medium size and Str 18",
	abilitytodamage : true,
	modifiers : ["", "Str-Dex"],
	ammo : "oversized arrow"
};
```

Unfortunately, this doesn't work if the weapon ever uses another ability score than Dex for its to hit. The sheet probably needs some extra functionality to make this weapon fully compatible.

**Comment by BraabHimself** [comment]
Ah, my bad.

I only did so under the advice of Smashman, unless I misunderstood him. I
thought it was weird that I'd need to upload those additional minified
files, as it would require you to inspect all of them.

>

**Comment by BraabHimself** [comment]
I somehow inadvertently closed this pull request. I don't know how I
managed that.

**Comment by safety-orange** [comment]
It seems that you removed the oversized longbow now from your branch. All the files in your branch and mine are identical, so there is nothing to merge :)

Just make another commit with the changed pub_20180918_WDH.js file.

**Pull request closed without merging**
